### ISSUE TITLE
Wrong evaluation order in multiple instructions

### ISSUE THREAD

**Issue by orlof** [azertyfun/DCPU-Toolchain#1]
in DCPU.java b operand and ex are evaluated in wrong order. e.g.

<pre>ADD ex, 0xffff</pre>

line 249

<pre>
case 0x02: //ADD
    cycles++;
    val = b + a;
    b = (char) val;
    ex = (char) (val >> 16);
    break;
</pre>

`
spec 1.7 implicitly states that ex is assigned after b operand. In these cases ex value is overwritten when b is assigned to ex.

**Comment by orlof** [comment]
Just reviewed the fix and it is not yet effective. I mean that line 390
`set(baddr, b);
`
is the one that overwrites the correct ex value with b operand value.

e.g.

```
                case 2:{ //ADD
                    cycles++;
                    int val = b + a;
                    b = (char)val;
                    set(baddr, b);
                    ex = (char)(val >> 16);
                    return;

```

**Comment by Yamakaky** [comment]
You mean it matters for example for `ADD EX, 1` which should set EX to 0 if EX < 0xffff?
Edit: yeah, that seems to be it. You set b at the end of the switch, to in `ADD EX, 1`, EX would be equal to EX+1.
@orlof is my implementation correct? https://github.com/Yamakaky/dcpu/blob/master/src/cpu.rs#L255

**Comment by Yamakaky** [comment]
I fail to see why someone would `ADD EX`, though ^^

**Comment by orlof** [comment]
I agree, it is a corner case.. but still a 🐛 
@Yamakaky it seems correct to me
