### ISSUE TITLE
Error in DIV emulation

### ISSUE THREAD

**Issue by orlof** [azertyfun/DCPU-Toolchain#2]
DIV implementation in DCPU.java is erranous. It uses (b << 16) to calculate ex. << operand converts b (char) into int32, which is signed. The signed int is then divided with a and the sign bit often pollutes the answer. b should be cast to long: ((long) b << 16) / a

**Comment by azertyfun** [comment]
Why should b cast to long? Since it is signed, it still shouldn't work.

Using the following program, `EX` is 0x8000 with `((long) (b << 16) / a)` **and** with `((b << 16) / a)`. However, if I cast `b` to a char (which is unsigned), `EX` is now 0x0000.

``` dasm
set A, 15
div A, 2
```

**Comment by orlof** [comment]
long works because when you shift bit15 to position 31 it does NOT change the sign of long. For int it does change it.

The difference can be seen with test program such 

<pre>
public class Div {
    public static void main(String[] args) {
        for(int a=1; a<0x10000;a++) {
            for(int b=0; b<0x10000;b++) {
                char aChar = (char) a;
                char bChar = (char) b;
                char ex32 = (char) ((bChar << 16) / aChar);
                char ex64 = (char) (((long) bChar << 16) / aChar);
                if(ex32 != ex64) {
                    System.out.println(b + " / " + a + " = " + (long) ex32 + " vs " + (long) ex64);
                }
            }
        }
    }
}
</pre>

**Comment by orlof** [comment]
I think that << operator will result int if left operand is char.

**Comment by Yamakaky** [comment]
Yeay no unsigned in java!
