### ISSUE TITLE
Wrong instruction length

### ISSUE THREAD

**Issue by orlof** [azertyfun/DCPU-Toolchain#3]
DCPU.java does not calculate instruction length correctly. If a or b operand is:

0x1a
[SP + next word] / PICK n

It does not add next word to the instruction length

**Comment by azertyfun** [comment]
What do you mean? PC is incremented when doing a `PICK n`, at [DCPU.java:565](https://github.com/azertyfun/DCPU-Toolchain/blob/master/src/tk/azertyfun/dcputoolchain/emulator/DCPU.java#L565).

**Comment by orlof** [comment]
I haven't tested this but I think this bug appears in following code:
`
IFE 0, 1
  SET a, [SP + 100]
`
In that case emulator is skipping and tick()->tick_skip()->getInstructionLength() will return wrong instruction length. I suppose it would next try to use 100 as instruction opcode and do something evil.
