### ISSUE TITLE
Shift behavior

### ISSUE THREAD

**Issue by orlof** [azertyfun/DCPU-Toolchain#4]
Java specification states explicitly that "only the five lowest-order bits of the right-hand operand are used as the shift distance". In DCPU specification there is no such statement. My interpretation is that shift distance is then defined with 16 bits. However, this is a bit unclear issue.

**Comment by azertyfun** [comment]
How does it affect the computation though?

If I run `SHR A, 20`, the result will be 0 whether I use five bits or not.

**Comment by orlof** [comment]
Java does the shift only with distance specified with 5 bits. e.g.
in Java's 5 bit shift distance 0xA0A0 << 0x20 is not 0x0000 but 0xA0A0 (equal to no shift)
You should have something like "if shift distance > 31 then result=0 else result =base<<distance"
